### ISSUE TITLE
Not authorized to perform: lambda:GetLayerVersion on resource

### ISSUE THREAD

**Issue by dawidsowardx** [ShivamJoker/Canvas-Lambda-Layer#2]
When I'm trying to deploy my stack with `canvas-lambda-layer` I'm getting following error 
```
|  API api/Lambda_GET_-- AWS::Lambda::Function CREATE_FAILED Resource handler returned message: "User: arn:aws:sts::0000000000:assumed-role/00000000-eu-west-2/AWSCloudFormation is not authorized to perform: lambda:GetLayerVersion on resource: arn:aws:lambda:us-west-2:205979422636:layer:napi-rs-canvas:886 because no resource-based policy allows the lambda:GetLayerVersion action (Service: Lambda, Status Code: 403, Request ID: 1c9d0ec9-c8aa-4cc8-9ada-7caba888186d)" (RequestToken: de00c22f-b7bc-cceb-7581-e8c7ca8a7288, HandlerErrorCode: AccessDenied) 
```

Is there anything I'm missing? I'm using arn from the same region as the region I'm trying to deploy to

**Comment by ShivamJoker** [comment]
The region is being mismatched, I'll try to deploy it some other regions as well.
Can you tell me what regions you'd like the layer to be in?

**Comment by dawidsowardx** [comment]
Oh, I just realized my brain skipped over `eu` compared to `us`. Can you try to deploy to `eu-west-2`?

**Comment by dawidsowardx** [comment]
@ShivamJoker Thanks for a quick response it was indeed just a region being mismatched. I'm happy to use one of the regions you've already provided!
